apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-gateway
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-gateway
  template:
    metadata:
      labels:
        app: cms-gateway
    spec:
      containers:
        - name: cms-gateway
          image: uhub.service.ucloud.cn/entropypool/cms-gateway:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/CMSGateway
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: cms-gateway-config
            items:
              - key: service-conf
                path: CMSGateway.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: cms-gateway
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50810
      targetPort: 50810
    - name: grpc
      port: 50811
      targetPort: 50811
    - name: healthz
      port: 50812
      targetPort: 50812
    - name: prometheus
      port: 50813
      targetPort: 50813
    - name: pub_grpc
      port: 50814
      targetPort: 50814
    - name: pub_http
      port: 50815
      targetPort: 50815
  selector:
    app: cms-gateway
